import type { User, SkillRequest } from "@/lib/types";

export const MOCK_USERS: User[] = [
  {
    id: "1",
    name: "Alice Johnson",
    email: "alice@example.com",
    location: "San Francisco, CA",
    skillsOffered: ["React", "Node.js", "GraphQL"],
    skillsWanted: ["Python", "Machine Learning"],
    availability: "Weekends",
    profile: "Public",
    profilePhotoURL: "https://placehold.co/100x100.png",
    rating: 4.8,
  },
  {
    id: "2",
    name: "Bob Smith",
    email: "bob@example.com",
    location: "New York, NY",
    skillsOffered: ["Data Analysis", "SQL", "Tableau"],
    skillsWanted: ["Web Design", "Figma"],
    availability: "Evenings",
    profile: "Public",
    profilePhotoURL: "https://placehold.co/100x100.png",
    rating: 4.5,
  },
  {
    id: "3",
    name: "Charlie Brown",
    email: "charlie@example.com",
    location: "Austin, TX",
    skillsOffered: ["Copywriting", "SEO", "Content Strategy"],
    skillsWanted: ["Photography", "Video Editing"],
    availability: "Flexible",
    profile: "Public",
    profilePhotoURL: "https://placehold.co/100x100.png",
    rating: 4.9,
  },
  {
    id: "4",
    name: "Diana Prince",
    email: "diana@example.com",
    location: "London, UK",
    skillsOffered: ["Project Management", "Agile", "Scrum"],
    skillsWanted: ["Public Speaking", "Leadership"],
    availability: "Weekdays",
    profile: "Private",
    profilePhotoURL: "https://placehold.co/100x100.png",
    rating: 4.7,
  },
    {
    id: "5",
    name: "Ethan Hunt",
    email: "ethan@example.com",
    location: "Paris, France",
    skillsOffered: ["UI/UX Design", "Figma", "Prototyping"],
    skillsWanted: ["Frontend Development", "JavaScript"],
    availability: "Weekends",
    profile: "Public",
    profilePhotoURL: "https://placehold.co/100x100.png",
    rating: 4.6,
  },
  {
    id: "6",
    name: "Fiona Glenanne",
    email: "fiona@example.com",
    location: "Miami, FL",
    skillsOffered: ["Spanish", "French", "Translation"],
    skillsWanted: ["German", "Italian"],
    availability: "Evenings",
    profile: "Public",
    profilePhotoURL: "https://placehold.co/100x100.png",
    rating: 5.0,
  },
];

export const MOCK_LOGGED_IN_USER = MOCK_USERS[0];

export const MOCK_REQUESTS: SkillRequest[] = [
    {
        id: 'req1',
        from: '2',
        to: '1',
        fromName: 'Bob Smith',
        toName: 'Alice Johnson',
        fromSkill: 'Data Analysis',
        toSkill: 'React',
        message: 'Hey Alice, I can help you with data analysis for your projects. I would love to learn React from you!',
        status: 'Pending',
        timestamp: new Date(Date.now() - 86400000 * 2),
        fromProfilePhotoURL: "https://placehold.co/100x100.png",
    },
    {
        id: 'req2',
        from: '3',
        to: '1',
        fromName: 'Charlie Brown',
        toName: 'Alice Johnson',
        fromSkill: 'SEO',
        toSkill: 'GraphQL',
        message: 'Hi, I saw you want to learn photography. I can teach you the basics. I am interested in learning GraphQL.',
        status: 'Accepted',
        timestamp: new Date(Date.now() - 86400000 * 5),
        fromProfilePhotoURL: "https://placehold.co/100x100.png",
    },
    {
        id: 'req3',
        from: '1',
        to: '2',
        fromName: 'Alice Johnson',
        toName: 'Bob Smith',
        fromSkill: 'Node.js',
        toSkill: 'Web Design',
        status: 'Pending',
        timestamp: new Date(Date.now() - 86400000 * 1),
        fromProfilePhotoURL: MOCK_LOGGED_IN_USER.profilePhotoURL,
    },
     {
        id: 'req4',
        from: '5',
        to: '1',
        fromName: 'Ethan Hunt',
        toName: 'Alice Johnson',
        fromSkill: 'UI/UX Design',
        toSkill: 'Node.js',
        message: 'Hi Alice, I am a UI/UX designer and can help you with your app design. I want to learn more about backend with Node.js',
        status: 'Rejected',
        timestamp: new Date(Date.now() - 86400000 * 7),
        fromProfilePhotoURL: "https://placehold.co/100x100.png",
    },
]
